
export const Courses =[
    {
        "id":1,
        "course_name":'Aws & DevOps Certification',
        "course_img":require('./assets/Course Images/AWSDevOps.png'),
        "course_link":"https://courses.microdegree.work/courses/aws-developer-certification-live",
        "course_desc":"Master AWS & DevOps from Cloud industry experts to become a solid Computing Professional",
        "course_category":'programming',
        "course_price":'20,000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":2,
        "course_name":'Power BI',
        "course_img":require('./assets/Course Images/powerBi.png'),
        "course_link":"https://courses.microdegree.work/courses/power-bi-tableau-certification",
        "course_desc":"Master Business Intelligence with Power BI & Tableau from Industry Experts to become a solid Professional in Data Visualization & Reporting",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":3,
        "course_name":'Automation Testing - Java',
        "course_img":require('./assets/Course Images/Java.png'),
        "course_link":"https://courses.microdegree.work/courses/automation-testing-java",
        "course_desc":"Master Automation Testing and learn most in-demand skills like Core Java, Selenium & Automation testing to become a solid QA Professional",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":4,
        "course_name":'Full Stack Web Development Certification',
        "course_img":require('./assets/Course Images/webDev.png'),
        "course_link":"https://courses.microdegree.work/courses/full-stack-web-development-certification",
        "course_desc":"Start with Basic HTML untill advanced Server Side Concepts with NodeJs & MongoDB to become a Expert MERN Stack Developer",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":5,
        "course_name":'Full Stack Data Science Certification',
        "course_img":require('./assets/Course Images/FullStackData.png'),
        "course_link":"https://courses.microdegree.work/courses/full-stack-data-science-certification",
        "course_desc":"Start with Basic Python until advanced Visualization Concepts with Power Bi to become a Data Science Expert",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":6,
        "course_name":'Technical Interview Preparation',
        "course_img":require('./assets/Course Images/Technical.png'),
        "course_link":"https://courses.microdegree.work/courses/technical-interview-preparation",
        "course_desc":"Start Cracking Technical Interviews like a Pro with this Basic to Advanced Interview Prep Course",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":7,
        "course_name":'Automation Java Testing Certification',
        "course_img":require('./assets/Course Images/Automatedjava.png'),
        "course_link":"https://courses.microdegree.work/courses/automation-java-testing-certification",
        "course_desc":"Start with Basic Manual Testing until advanced Selenium Automation to become a Expert Automation Tester",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":8,
        "course_name":'DevOps Certification',
        "course_img":require('./assets/Course Images/DevOpsRecorded.png'),
        "course_link":"https://courses.microdegree.work/courses/devops-certification-live",
        "course_desc":"Master on-demand skills from Industry Experts to become a solid DevOps Professional",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":9,
        "course_name":'AWS Certification ',
        "course_img":require('./assets/Course Images/AWSRecorded.png'),
        "course_link":"https://courses.microdegree.work/courses/aws-certification-live",
        "course_desc":"Master AWS from industry experts to become a solid Cloud Computing Professional",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":10,
        "course_name":'Python Certification',
        "course_img":require('./assets/Course Images/Python.png'),
        "course_link":"https://courses.microdegree.work/courses/ython",
        "course_desc":"Learn Python from scratch and build interactve projects. Kick-start your journey into the world of Data Science and Machine Learning here.",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":11,
        "course_name":'MySQL Certification',
        "course_img":require('./assets/Course Images/MySQL.png'),
        "course_link":"https://courses.microdegree.work/courses/mysql",
        "course_desc":"Learn Python from scratch and build interactve projects. Kick-start your journey into the world of Data Science and Machine Learning here.",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
    {
        "id":12,
        "course_name":'Data Analytics Certification',
        "course_img":require('./assets/Course Images/dataAnalytics.png'),
        "course_link":"https://courses.microdegree.work/courses/data-analytics",
        "course_desc":"Dive into the world of Data Science with hands-on exposure to real-world data sets & gear up for your dream data career.",
        "course_category":'programming',
        "course_price":'15000',
        "course_status":"live",
        course_details:["60 Hrs of LIVE Online Training",
        "Concepts Explained in Kannada",
        "Completion Certificate",
        "Build Interactive Projects",
        "Doubt Clarification",
        "Interview Preparation",
        "Career Assistance",
      ],
    },
]